# app.py  — cv2-free, works on Python 3.14
import streamlit as st
import numpy as np
import time
import pandas as pd
from datetime import datetime
from PIL import Image
from detector.yolo_detector import detect_objects
from utils.alerts import should_alert, play_alert_sound
from utils.summary import init_summary

st.set_page_config(page_title="VisionGuard AI", layout="wide", page_icon="👁️")

st.markdown("""
<style>
    .alert-high { background:#ff4b4b22; border-left:4px solid #ff4b4b; padding:10px 16px; border-radius:4px; }
    .risk-high   { color:#ff4b4b; font-weight:600; }
    .risk-medium { color:#ffa500; font-weight:600; }
    .risk-low    { color:#21c55d; font-weight:600; }
</style>
""", unsafe_allow_html=True)

# ── SIDEBAR ──────────────────────────────────────────────────────────────────
with st.sidebar:
    st.image("https://img.icons8.com/fluency/96/eye.png", width=60)
    st.title("VisionGuard AI")
    st.caption("Real-Time Detection System")
    st.divider()
    st.subheader("⚙️ Detection Settings")
    confidence_threshold = st.slider("Confidence threshold", 0.1, 0.9, 0.4, 0.05)
    proximity_threshold  = st.slider("Alert distance (meters)", 1.0, 20.0, 7.0, 0.5)
    sound_enabled = st.toggle("🔊 Alert sound", value=True)
    st.divider()
    st.subheader("🎨 Risk color legend")
    st.markdown('<span class="risk-high">● HIGH</span> &nbsp; < 4m', unsafe_allow_html=True)
    st.markdown('<span class="risk-medium">● MEDIUM</span> &nbsp; 4–7m', unsafe_allow_html=True)
    st.markdown('<span class="risk-low">● LOW</span> &nbsp; > 7m', unsafe_allow_html=True)
    st.divider()
    st.markdown("""
    **VisionGuard AI** detects pedestrians and vehicles using YOLOv8.
    - 🚶 Proximity-based alerts
    - 🚗 Vehicle detection
    - 📊 Live analytics
    - 📥 CSV & report export

    Built with YOLOv8 · Streamlit
    """)
    st.caption("VisionGuard AI v2.0")

# ── SESSION STATE ─────────────────────────────────────────────────────────────
if "summary" not in st.session_state:
    st.session_state.summary = init_summary()
if "fps_list" not in st.session_state:
    st.session_state.fps_list = []
if "last_frame_time" not in st.session_state:
    st.session_state.last_frame_time = time.time()

# ── HEADER ────────────────────────────────────────────────────────────────────
st.title("👁️ VisionGuard AI")
st.subheader("Real-Time Pedestrian & Vehicle Detection System")
st.divider()

# ── METRICS ───────────────────────────────────────────────────────────────────
m1, m2, m3, m4, m5 = st.columns(5)
ped_m  = m1.empty()
veh_m  = m2.empty()
alr_m  = m3.empty()
fps_m  = m4.empty()
tot_m  = m5.empty()

def update_metrics(summary, fps=0.0):
    ped_m.metric("🚶 Pedestrians", summary["pedestrians"])
    veh_m.metric("🚗 Vehicles",    summary["vehicles"])
    alr_m.metric("🚨 Alerts",      summary["alerts"])
    fps_m.metric("⚡ FPS",          f"{fps:.1f}")
    tot_m.metric("📦 Total",        summary["total"])

update_metrics(st.session_state.summary)
st.divider()

input_type = st.radio("Select input type", ["Upload Image", "Upload Video"], horizontal=True)
frame_placeholder = st.empty()
alert_box         = st.empty()

# ── HELPERS ───────────────────────────────────────────────────────────────────
def compute_fps():
    now = time.time()
    elapsed = now - st.session_state.last_frame_time
    st.session_state.last_frame_time = now
    fps = 1.0 / max(elapsed, 0.001)
    st.session_state.fps_list.append(fps)
    if len(st.session_state.fps_list) > 30:
        st.session_state.fps_list.pop(0)
    return round(sum(st.session_state.fps_list) / len(st.session_state.fps_list), 1)

def trigger_alert(summary):
    alert_box.markdown(
        '<div class="alert-high">🚨 <b>Pedestrian too close! Immediate danger.</b></div>',
        unsafe_allow_html=True
    )
    if sound_enabled:
        play_alert_sound()

def export_csv(summary):
    if not summary["detection_log"]:
        return None
    return pd.DataFrame(summary["detection_log"]).to_csv(index=False).encode("utf-8")

def export_txt(summary):
    lines = [
        "=" * 50,
        "       VISIONGUARD AI — DETECTION REPORT",
        "=" * 50,
        f"Session start : {summary['start_time']}",
        f"Report time   : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "", "SUMMARY", "-" * 30,
        f"  Pedestrians : {summary['pedestrians']}",
        f"  Vehicles    : {summary['vehicles']}",
        f"  Total       : {summary['total']}",
        f"  Alerts      : {summary['alerts']}",
        "", "DETECTION LOG", "-" * 30,
    ]
    for e in summary["detection_log"]:
        lines.append(f"  [{e['time']}]  {e['type']:12s}  dist={e['distance_m']}m  risk={e['risk'].upper()}")
    lines += ["", "=" * 50, "  Generated by VisionGuard AI v2.0", "=" * 50]
    return "\n".join(lines).encode("utf-8")

def show_log_and_export(summary):
    st.divider()
    st.subheader("📋 Detection history log")
    if summary["detection_log"]:
        df = pd.DataFrame(summary["detection_log"])
        df.columns = ["Time", "Type", "Distance (m)", "Risk"]
        df["Distance (m)"] = df["Distance (m)"].astype(str)
        def color_risk(val):
            return {"high": "color:#ff4b4b", "medium": "color:#ffa500", "low": "color:#21c55d"}.get(str(val).lower(), "")
        st.dataframe(df.style.map(color_risk, subset=["Risk"]), use_container_width=True, hide_index=True)
    else:
        st.info("No detections yet.")
    st.divider()
    st.subheader("📥 Export report")
    c1, c2 = st.columns(2)
    with c1:
        csv = export_csv(summary)
        if csv:
            st.download_button("⬇️ Download CSV", data=csv,
                file_name=f"visionguard_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv",
                mime="text/csv", use_container_width=True)
        else:
            st.button("⬇️ Download CSV", disabled=True, use_container_width=True)
    with c2:
        st.download_button("⬇️ Download Report (.txt)", data=export_txt(summary),
            file_name=f"visionguard_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
            mime="text/plain", use_container_width=True)

# ── IMAGE MODE ────────────────────────────────────────────────────────────────
if input_type == "Upload Image":
    if st.button("🔄 Reset session"):
        st.session_state.summary = init_summary()
        st.rerun()

    image_file = st.file_uploader("Upload an image", type=["jpg", "png", "jpeg"])
    if image_file:
        pil_img = Image.open(image_file).convert("RGB")
        frame   = np.array(pil_img)
        summary = st.session_state.summary

        t0 = time.time()
        frame, alert = detect_objects(frame, summary, confidence_threshold, proximity_threshold)
        fps = round(1.0 / max(time.time() - t0, 0.001), 1)

        frame_placeholder.image(frame, width="stretch")
        update_metrics(summary, fps)

        if alert and should_alert():
            trigger_alert(summary)

        show_log_and_export(summary)

# ── VIDEO MODE ────────────────────────────────────────────────────────────────
elif input_type == "Upload Video":
    if st.button("🔄 Reset session"):
        st.session_state.summary = init_summary()
        st.rerun()

    video_file = st.file_uploader("Upload a video", type=["mp4", "avi", "mov"])
    if video_file:
        # cv2 used only here for video — import locally so image mode still works
        import cv2
        with open("temp_video.mp4", "wb") as f:
            f.write(video_file.read())

        summary = st.session_state.summary
        cap = cv2.VideoCapture("temp_video.mp4")

        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break
            # cv2 gives BGR — convert to RGB for PIL-based detector
            frame_rgb = frame[:, :, ::-1]
            frame_rgb, alert = detect_objects(frame_rgb, summary, confidence_threshold, proximity_threshold)
            fps = compute_fps()
            frame_placeholder.image(frame_rgb, width="stretch")
            update_metrics(summary, fps)
            if alert and should_alert():
                trigger_alert(summary)
            time.sleep(0.03)

        cap.release()
        show_log_and_export(summary)